<!--
This is for including Chapter 1.  Notice that it's also good practice to name your chunk.  This will help you debug potential issues as you knit.  The chunk above is called intro and the one below is called chapter1.  Feel free to change the name of the Rmd file as you wish, but don't forget to change it here from chap1.Rmd.
-->

<!--
The {#rmd-basics} text after the chapter declaration will allow us to link throughout the document back to the beginning of Chapter 1.  These labels will automatically be generated (if not specified) by changing the spaces to hyphens and capital letters to lowercase.  Look for the reference to this label at the beginning of Chapter 2.
-->

```{r knitr-setup, echo=FALSE}
knitr::opts_chunk$set(
  comment = "#>", 
  echo = FALSE, 
  out.width = "0.85\\linewidth")
```

# Introduction

## Introduction

Stress and associated consequences, as an inevitable part of daily life and in work, society, economy and so on, have been investigated in various fields such as psychological, sociological and physiological studies.

In addition to stress-related factors such as workplace and labor market, personal characteristics, environmental, and interpersonal factors, commuting plays a significant role as a source of stress, classified into objective stressors and subjective moderators. The first category called impedance, includes commuting condition-related factors such as commuting time, distance or speed and the second one refers to the perception and feeling of control over the commute, predictability of the journey’s conditions and personal characteristics like gender, income and age [@gottholmseder2009stress].

Nowadays commute has become all-pervasive for a large portion of people to reach their destinations and correspondingly commuting stress will affect a huge number of people [@legrain2015stressed]. Understanding the interaction between specified demographic and stress-related factors along with the associated coping strategies, is the main goal of this research. Apart from this, the goal of the study is also extended to analyze the method that people use to address their stress and deal with negative feelings while commuting regarding the attached importance of stress by them. The research findings suggest that commuters interested in public modes are the most suffering category while they sometimes have no choice. 

This fact can be in accordance with research findings as the income of most residents of Santiago can be categorized into low and middle levels. It is also inevitable for people who live long distances from their workplace to use available motorized options such as public ones. The novelty of the research is to simultaneously investigate stress caused by travel, to what extent this importance is tangible based on a bivariate ordinal regression model, also what coping strategies apparently have been used in Santiago, Chile. The health information for this research has been extracted from a survey conducted in Santiago, Chile. This survey has been shaped into a reproducible data set for future research.  

## Background

As @novaco2009commuting have mentioned regarding the historical background of the contribution of psychology in transportation, although the field of transportation has been dominated by urban planners, engineers and economists, the contributions of psychologists and sociologists have been blended into this arena. @novaco2009commuting also indicated that as families, individuals and organizations were concerned about the hidden costs of traffic congestion, air pollution and noise, it can be important to investigate how to optimize transportation systems and evaluate the impacts of travel constraints. Also they indicated in their research that the contribution of psychologists in transportation began in the 1920s when transportation firms and government agencies looked for improvement in driver selection of public transport vehicles and employed psychometric tests to choose the operators. 

@novaco2009commuting also pointed out that the term "commuting stress" has been mentioned in a very appropriate way in the book by Koslowsky, Kluger, and Reich (1995, as cited in Novaco & Gonzalez, 2009), who provide an engaging composition of the environmental, psychological, personal health, and organizational factors involved. They offer an elaborate structural model and provide a rich discussion of coping at both the individual, organizational, and governmental levels. 

Over the years commuting stress has been increasingly taken into consideration in research whereas it has been recently proposed to integrate bivariate or multivariate relationships between commuting variables and outcome measures. 

According to the model presented by @koslowsky1997commuting to understand the relationship among commuting variables, moderators, and outcome variables, it is expected to explain the impact of stress on people's travel behaviour. As commuting experience may have a highly significant effect on commuters in terms of psychological, physiological and behavioural factors, a comprehensive model would be beneficial to understand the linkages among them and to develop coping strategies based on that. As it has been previously indicated subjective refers to personal perceptions and cognitive appraisal, while objective stressors primarily refer to the condition of travel such as time and distance between work and home or even speed of travel. 

The necessity of including both characteristics in the modelling process has been indicated according to a notion explaining the lower error in strain prediction after adding subjective outcomes as both subjective and objective stressors are required to predict their related responses which cannot be covered by only one of them [@koslowsky1997commuting]. 

The moderator as another component of this model interacts with independent variables to influence an outcome which cannot be predicted by each one of the variables alone. This study covers a number of commuting stressors such as stress while commuting and the assigned importance level to this as a negative experience by commuters and the interaction of them with moderators such as income, age and choice of transportation mode to understand how commuters in Santiago, Chile deal with commuting stress. 

In terms of the method for dealing with stress among travelers, the concept of normalization as a coping strategy derived from mobility research would be responsive as it is able to moderate both stress and stimulation during a trip. Normalization tries to remove the stimulating and rewarding dimensions of travel.This is a multifaceted process which happens on many levels and may have both positive and negative outcomes for commuters [@gustafson2014business].
Stress-coping theory splits into problem-focused and emotion-focused strategies. The former seeks to tackle the problem by doing an act such as taking advantage of the radio to be more aware of the conditions of travel and traffic ahead, listening to music when driving to make people anxious or changing the mode of transport to experience less negative effects of travel. While emotion-based coping strategies concentrate on minimizing the emotional outcomes of the problem through various mental processes such as wishful thinking, self-blame and avoidance [@nakano1991role]. 

According to the current research's findings, while a group of people experience high levels of stress, they may have no more options to avoid stress and to some extent will continue using the same stressful mode of transport.

As @gustafson2014business mentioned, the concept of normalization of travel can be observed on three different levels societal, organisational and individual level. 

The first level happens on the level of society where leisure travel is becoming ubiquitous and more exciting than work-related travel. Previously people could not travel as much as nowadays because of financial matters or other issues. But these days travelling has become more prevalent even travelling for work due to economic and political internationalization as well as organizational trends reinforcing the normalization of travel on a societal level.

The second level of normalization can be seen on an organizational level. Travel based on occupational targets has been increased and has become a more normal activity in organizations. 

The individual level is the third level of normalization to be appeared on. People's experience of travel extensively varies from one to another as some of them consider it as a routine and normal component of daily life due to the high repetition of the activity such as business travels. Normalization may have multiple and apparently paradoxical consequences. Thanks to the normalization some individuals may experience less stressful travels and learn how to manage travel-related practicalities. The term "travel competence" as an appropriate example accounts for the positive side of employing the concept of normalization leading to less annoying travel. However, it has been indicated that normalization simultaneously may deprive people of experiencing excitement and fade the attraction away. 

As stress and coping strategies have been considered key determinants of public health and life quality, this area of research has become significant in both theoretical and practical implications. Investigating the methods of dealing with stress by people would be advantageous in understanding the mechanism by which coping strategies address the negative impact of stress on health and well-being. Also, this knowledge would be useful for the development of effective health-related policies and programs to prevent stress-induced illnesses, decrease health service expenses and boost public health [@iwasaki2005gender].

The study here will focus on analyzing the subjective moderators and commuting stress-related variables regarding the literature. Modelling the process based on our outcome and exploratory variables may consider both theoretical and empirical implications beneficial in understanding the coping mechanism for an expected cluster of commuters. 

## Thesis rationale 

Certainly, it is important to understand and identify the variables affecting commuting stress and the relevant coping strategies. For instance, perceived stress during trips would have serious social and public health implications. Accordingly, by investigating the stress across different mode choices, the strongest contribution of that particular mode to the potential health and social issues can be indicated. In a study conducted by @legrain2015stressed this process is done by using an ordered logistic regression to develop a general model of stress and three mode-specific models. This study concluded that driving is the most stressful mode of transportation compared to any other options and the stressors vary from one mode to another. 

The knowledge of specific factors indicating that a certain mode is stressful will help transportation and public health experts make travelling a more safer, exciting and less stressful activity helpful in minimizing potential health outcomes of a stressful commute. Specifically, having this knowledge allows them to mitigate stressors such as crowded conditions, long waiting times, and uncomfortable seating. Income also has been indicated as an influential variable in identifying the effect of commuting time and accordingly commuting stress on salary satisfaction. @sha2019beyond found that salary satisfaction is highly significant when it comes to the mediation of the association between commuting time and life satisfaction. The knowledge of the interaction between commuting time and subjective well-being is of high importance when formulating policies. As commuting stress has been specified to be generated by prolonged commuting time, the satisfaction of salary and consequently life satisfaction may decrease. 

In another study, @useche2023another identified that age differences coherently are associated with commuting stress as previous literature has pointed out. Individuals in different age groups vary in terms of cognitive appraisal of commuting stress. They also found that the association between age and commuting stress tends to be negative and younger commuters may remain the most affected group to address the issue by commuter stress-alleviating actions and interventions. @westerman2000individual reported that there are age-related changes in driving behavior. For example, older individuals tend to drive more slowly, potentially compensating for intense feelings of stress during commuting.



## Chapter Objectives and Contents

This research aims to investigate the perceived commuting stress among active and motorized commuters and the relevant coping strategies. The specific objectives are as follows: 

- To develop a reproducible data package including various travel behavioral and psychological aspects of commuters' daily movements.

- To analyse the interaction between stress-related outcomes and exploratory variables.


- To identify coping strategies for a particular group of commuters and specifically how people's attitude differs in terms of demographic characteristics.

## Thesis Content

The following chapters of thesis are organized as follows:

Chapter 2 contains a comprehensive and reproducible data package including commuters' experiences of living and moving in an urban environment such as socio-economic and demographic information, feelings and emotions, various self-assessed health questions and so on. This information was gained through a traditionally conducted survey with a notable number of respondents providing a nice foundation of psychological and demographic information for the subsequent chapter. 

Chapter 3 includes an exploratory analysis of perceived stress by motorized and active commuters and the importance of the experienced stress assigned by them. This analysis will be done using a modelling process to identify the relevant exploratory variables. furthermore, this chapter assesses the significant role of coping strategies and tries to understand the methods used by people to cope with stressful commuting. 

The last chapter concludes the research using a brief overview of the contents accompanied by the thesis contributions. This chapter also discusses the study's limitations and potentials for further research in terms of investigating commuting stress and coping strategies.
