# Conclusion

The knowledge of commuting stress in both psychological context and travel behaviour studies is of importance as it tends to have a significant impact on daily patterns of commute. This thesis focuses on the analysis of the interaction between demographic specifications, stress feelings towards the travel experiences and their reaction.

Chapter two contributes to constructing a comprehensive foundation in the format of a reproducible data package including a wide variety of aspects of living and moving in the urban environment. As it has been indicated earlier, people may have different travel experiences in terms of perceiving stress and assigning importance to negative feelings regarding their occupation, age, income and mode of transportation choice. Chapter three includes modelling techniques to understand the interaction between our outcome and exploratory variables to identify how commuters based on different categories are affected and what coping strategies can be applied to them.

In the following sections of this chapter, the mentioned contributions will be discussed in depth along with policy implication of the research, study limitations and further research.

## Research Contribution

Research primarily aimed at exploring travel behaviour and commuting stress on a daily basis. This thesis also contributes to understanding the coping strategies that may have been used by commuters.

### Providing a Reproducible Data Package based on the Travel Behaviour of Santiaguinos Commuters.

The research is based on a large-scale and purposefully collected travel survey including a broad range of various information on health, demographics, feelings and emotions, the built environment and so on. Given the survey as the foundation of this research, the study has contributed to providing a reproducible data set by performing different steps of data cleaning, documentation, storage and version control. These measures led to the establishment of valuable open source data, helpful to understanding travel behaviour and commuting experiences of Santiago for future works. The feelings and emotions part of the survey helps investigate the effect of commuting on stress for both motorized and non-motorized commuters. This information gives beneficial insights to decision-makers in transportation planning, public sector development and stress-related policies to improve the commuting experience and make it safer and less stressful.  

### Influential Attributes in Commuting Stress Experiences

Findings based on the bivariate ordinal regression model suggested that people may have different feelings from happiness and excitement to anxiety and stress according to various socio-demographic situations such as different age groups, occupations, income levels and the primary mode of transport choice. In terms of the importance of understanding the possible stressors, @useche2023another found that while commuters encounter daily negative commute experiences such as traffic jams, deficiencies in transport choices, crowded public transport services, prolonged trips, and road conflicts, there are not many studies that have methodologically addressed the issue of commuting stress (CS). Findings of the current study have indicated that mostly pertaining to lower levels of income, young age range, using public modes may cause people to feel more stress while considering not enough importance to that feeling.

### Potential Coping Strategies

According to the results from the modelling process and exploring the previous studies in terms of the ways that people deal with stress, the concept of normalization as an emotion-based coping strategy has been indicated to be employed by commuters. As indicated earlier almost more than half of Santiaguinos are related to middle-income and low-income and had limited transportation options. As @chen2017travel found, work-related travel may be integrated with stress and this negative feeling of travellers can be rationalized and adjusted leading to normalization. Business travellers may experience different levels of stress than leisure commuters and they know how to develop strategies to normalize the stress that they are facing. Hence, understanding various aspects of work commuters’ stressors is important to address their issue associated with commuting stress.

## Policy Implications

### Invest in Public Transport Infrastructure

As the results from the modelling process of this dissertation have indicated, almost more than half of the respondents were characterized as middle-income and low-income people who relied on using public modes of transport for daily work commutes. The findings also revealed that although the youth age range is the most stress-affected commuters out of these people, they did not care about the feeling of stress as they were assumed to be. Following this issue, enhancement in public transportation infrastructure could be considered as a crucial policy implication in research. According to commuters’ experiences, having access to more reliable, efficient, and comfortable public transportation can reduce the stress associated with commuting, especially for those who rely on it such as younger people from middle-income and low-income groups in this research. Policymakers should consider that investments in public transit can lead to reduced congestion, shorter commute times, and a more positive and satisfying commuting experience.

### Promote Alternative Transportation Modes

The results of the thesis suggested that active transport modes like walking or cycling are the least popular modes in Santiago. Interestingly, this mode is mostly used by low-income categories who are more conscious of the importance of stress but experience relatively lower stress levels as opposed to those from the same group but with high stress and interested in public mode. As similar Chilean studies like @herrmann2020persistence have shown the unpopularity of active transportation can be attributed to safety concerns, including sexual harassment, and a lack of safe infrastructure. Thus, encouraging the use of alternative and healthy transport modes like cycling and walking, and even carpooling would be another key policy implication. These modes can reduce the stress of daily commuting, help promote physical activity and contribute to environmental sustainability. Hence, policies that create safe and convenient options for active transportation can significantly impact commuters' well-being and reduce commuting stress.

## Further Research

The research analyzed the impact of stress on commuters on a daily basis by investigating the interaction among experienced stress, the importance of that and socio-demographic variables to understand the relevant coping strategies to address this issue. However, some other research questions need further attention.

### Exploring Cross-Cultural Impacts on Travel Patterns and Commuting Stress

Understanding the cross-cultural differences in commuting stress and coping strategies can be helpful in studying how individuals in different cultural contexts experience and manage the stress associated with their daily commutes. Furthermore, it can be explored whether various cultural factors, such as societal norms and lifestyles, values, and communication styles, influence how people perceive and cope with commuting stress. For instance, @balbontin2021impact has investigated cross-cultural comparisons using data from eight countries (Argentina, Australia, Brazil, Chile, Colombia, Ecuador, Peru and South Africa). They explored the incidence of remote working post-COVID-19 and what impact this could have on the number of weekly commuting trips. Therefore, exploring the changes in travel behaviour and commuting stress due to various reasons and in different cultural contexts would be beneficial in understanding and predicting new trends. 

### The Role of Technology in Commuting

According to the literature review in this research, people differ in employing a technique to deal with their stressful experience of commuting. Some of them may take advantage of problem-focused and others would be interested in using emotion-focused coping strategies. As a result, further research area could investigate the role of technology in modern commuting experiences, including the impact of digital gadgets and interventions on the way that people deal with negative feelings when travelling. Regarding the increasing use of technology in daily life, understanding commuters’ interactions with these digital tools during travel is important. As @holden2018technology has pointed out while stress can have a negative effect on work-life balance, technology would have an improving role on that. For example, people can undertake their job responsibilities using a phone, avoid commuting stress, allocate their time to other activities and manage both work and life commitments in a more flexible way.

### Impacts of Environmental Factors on Commuting Experiences

According to the Santiago data set as a foundation for further analysis, sections of built environment and nature and sustainability of the city people reveal different viewpoints about the effect of the physical environment of commuting routes and individuals' experiences during their commutes. Investigating an appropriate way to manage the problem of stress requires further research and development of appropriate interventions. As @rowden2011relative has suggested, interventions may aim at environmental factors such as traffic congestion, mitigating stress responses (e.g., work-related stress management programs), or enhancing the driver's ability to cope with challenges during the commute.

## Study Limitations

Some main limitations of this study should be considered. First, there was a shortage of stress-specific and objective stressor variables in our data set such as speed, level of traffic congestion, commute starting and ending times, commute duration and so on. Having comprehensive collected data can provide a better understanding of how commuting stress affects commuters and what type of coping strategies they tend to employ.

Second, is the lack of variation in coping strategy identification in terms of introducing specific coping strategies regarding each mode of transportation. As the research focused on the most affected group of people who were public transport commuters, other significant modes like private ones were excluded while public commuters had negative feelings of stress during their commute. 

The third one is related to the collection date of the data set used as a foundation for the second paper. The survey was conducted a couple of years ago when there was no impact of COVID-19 on the travel behaviour of Santiaguinos. COVID-19 has significant impacts in terms of changing travel patterns as a notable portion of people have transitioned to remote jobs or some others have reduced their dependency on using public transportation. Therefore, incorporating COVID-19-related variables will be helpful in providing more accurate insight into travel behaviour and health and safety concerns.

## Closing Remarks

This thesis aims to investigate the effect of stress on the commuting experience of motorized and non-motorized commuters and how they address their negative feelings.  As the study has indicated understanding mode of transport choice and income level would be important as these variables have an impact on the stress level during the commute. Public transport users, who are mostly low-income individuals, experience the highest levels of commuting stress. This category of commuters seems to be more resilient to stress, perhaps because of the necessity of using public transport regarding their financial status despite its drawbacks. In contrast, private transport users who are mainly high-income, also face substantial stress, indicating that higher income does not necessarily mean experiencing stress-free commuting. @evans2002morning also pointed out an interesting explanation about the role of the degree of predictability as a salient contributor to commuting stress in commuter mode selection. Perhaps private mode users are more interested in using their own vehicle than public means of transportation because they feel more predictability than mass transit options.

The thesis also investigated the role of normalization as a coping mechanism. The concept of "limited horizons" and normalization appear as a well-fitted coping mechanism. Low-income commuters, despite undergoing high stress levels, reveal a level of adaptation or normalization, possibly resulting from their reliance on public transport. This normalization process has been indicated to be beneficial for them to deal with daily stressors associated with commuting.

Age as another influential demographic characteristic on stress perception has been reviewed in this study. Younger commuters, especially those relying on public transport, have reported the highest stress levels but have assigned the least importance to their negative feelings. This generation seems to be more resilient or indifferent to commuting stress compared to their counterparts. Contrastingly, adults as a category who are primarily using private transport, have undergone less stress but they have prioritized addressing it, revealing a greater concern for their well-being.

These findings emphasize the complex interaction among socioeconomic factors, mode of transport choice, and stress perception in the context of daily commuting. Furthermore, the importance of considering psychological aspects and adhering to them as coping strategies, such as normalization has been indicated when it comes to designing policies and interventions to enhance commuting experiences and feelings. Understanding these dynamics can inform policymakers and transportation planners as they work towards creating more equitable, efficient, and less stressful transportation systems. For instance, @smith2017commute has indicated that policymakers should continue to make active travel options more available as people feel happier commuting by bike or walking. Future research could delve deeper into the decent coping mechanisms employed by different commuter groups and explore how these findings can be used in other global contexts.

