---
title: 'A Study on Commuting-Induced Stress and Coping Strategies in Santiago, Chile'
author: 'Niloofar Nalaee'
#date: 'May 20xx'
university: 'McMaster University'
faculty: 'Faculty of Science'
department: 'School of Earth, Environment and Society'
subject: 'Geography'
supervisor: 'Antonio Paez'
bdegree: 'B.Sc.' # Bachellor's Degree
mdegree: ''   # Master's Degree (if any)
# This is the degree you are aiming for with this thesis
degree: 'M.Sc.'

knit: bookdown::render_book
site: bookdown::bookdown_site

# Remove the hashtag to specify which version of output you would like.
# Can only choose one at a time.
output:
  thesisdown::thesis_pdf: default 
  keep_tex: true
#  thesisdown::thesis_gitbook: default         
#  thesisdown::thesis_word: default
#  thesisdown::thesis_epub: default

# If you are creating a PDF you'll need to write your preliminary content 
# (e.g., abstract, acknowledgements) below or use code similar to line 25-26 
# for the .RMD files. If you are NOT producing a PDF, delete or silence
# lines 31-56 in this YAML header.
lay_abstract: |
  Nowadays commuting as a daily travel mostly beween work and home is considered as an inevitable part of modern lifestyle. This experience   has been indicated to be a source of stress and anxiety as numerous studies have already revealed. Understanding commuting patterns and     travel behavior is important for analyzing stress-related issues, consequenses and coping strategies. As @koslowsky2013commuting has      mentioned, this is also beneficial to have a perception of commuting patterns, mode of transportation, road congestion and so on for        commuting network planning from scratch. Using the relevant stress commuting variables such as experienced stress and assigned importance   to this stress can help to this end.
  
  This research aimed at providing a comprehensive and reproducible data package of travel behavior and other aspects of the urban commuting experience of     respondents in Santiago, Chile. Each components of this data package serves different aspects for future research such as using             demographic information in travel demand modeling,  health-related information for improving health, well-being and safety in               transportation planning, reasons and planning decisions information for origin-destination modeling, and so on.
  
  The research also has been focused on an integrated list of variables choosen from demographic and health information sections of the data   package. This list helps to identify how commuters interact with experiencing stress during their travels. This research also contributes   to address commuting stress by identifying relevant variables, then figuring out the affected groups and analyzing their coping             strategies. 
abstract: |
  The research examines the effect of commuting on stress for both motorized and non motorized commuters and understanding how they cope with it. Understanding this effect can be helpful for decision makers in economy, transportation planning, and demographics studies to promote a safe and peaceful experience of travel for all the commuters in community by designing better transportation systems and developing infrastructure of alternative modes like walking. Moreover, understanding the emotional states of individuals   during their journeys and how they navigate and manage the commuting stress feeling, can be beneficial for decision makers to enhance commuting experiences and feelings.
  
  To this end, a bivariate ordinal model was adopted, allowing for an analysis of stress factors and their interactions with key exploratory variables, including income, age, and choice of transportation mode. Interestingly, the results obtained from the context of Santiago, Chile, a region characterized by a predominance of middle and low-income populations according to the research findings, revealed intriguing patterns. The study found that commuting stress influence people in different way regarding their age. Moreover, commuting stress at higher levels decreases at elevated age levels. This trend remains steady as commuters gain higher economic status and have access to alternative modes of transportation beyond public means. Policymakers and transportation planners should consider the complex interplay of two following clusters according to the result of this research to improve commuting experiences. The first encompasses factors such as income status, choice among different modes of transportation, and age. The second pertains to commuting stress and importance of stress from commuters' viewpoint. A salient example of the consequence of this interplay, is evident in the research, where normalization a coping strategy implying on eliminating some aspects of travel, is employed, showcasing both potential advantages and drawbacks. The findings suggest that promoting active travel options could contribute to a happier commuting experience, emphasizing the importance of understanding coping mechanisms across different commuter groups for the design of effective policies.
  
  The implications of these findings extend to the domain of transportation system planning and urban development. By shedding light on the challenges caused by commuting stress and highlighting effective coping mechanisms, this research holds the potential to understand how people deal with commuting stress during their regular trips. Furthermore, the gained insights can inform urban planning initiatives and facilitate the commuting experience by considering commuters' experiences and the associated factors. Ultimately, the integration of these insights into policies and practices has the capacity to cultivate sustainable and resilient communities, which thrive even when facing the inevitable stresses associated with daily commuting.
  
  This research makes a two-fold contribution. First, it compiles an extensive array of data including socio-demographics, health metrics, feelings and emotions, built environment, and work commute-related details, all presented in a comprehensive and reproducible data package format.  Subsequently, the study delves into the commuting stress analysis and identifying the various coping strategies employed by commuters. The data used for the analysis have been derived from the demographics and health information sections of the dataset. Serving as a reproducible data package, it provides a robust foundation for future research endeavors. Future researchers can have access to the data set as an open source data set allowing them to understand the representativeness of this data package and enable them to replicate various stages where needed.
acknowledgements: |
  Through the completion of this research, I have acquired numerous invaluable skills and cherished attributes. The journey has granted me a   deeper patience and a higher comprehension of the interaction between different scopes of research like psychology and travel behavior.     This experience has significantly broadened my horizons specially to grasp the essential but neglected elements of transportation           planning.
  
  I would like to express my deepest gratitude to my supervisor, Dr. Antonio Páez, for his endless encouragement, support, and for guiding    me  in the direction I needed to follow. His mentorship has been precious, and his insights have not only lightened my academic path, but   also  would be as a treasure for my future career. I am also extremely thankful to my esteemed examiners, Dr. Scott, Dr. Léa Ravensbergen,   and Dr.  Luc Bernier as the chair of the Master's Defence Committee, for their presence on my committee, thoughtful considerations and their constructive feedbacks on my master's proposal     meeting.  Their expertise and guidance have undoubtedly enhanced the quality of my research. My success would not have been possible        without the support of, Dr. Beatriz Mella-Lira who had a fundamental role in my research by providing the survey, endless support and       patience while answering my questions.
 
  I extend my sincere appreciation to my friends, with a special gratitude to Dr. Shaila Jamal. Her consistent presence, insightful           consultations, and valuable perspectives have been a constant source of support for me. Additionally, I would like to acknowledge Dr.       Samira Hamidi Tehrani for her boundless assistance, guidance, and remarkable patience and allocated time to me during the times when I      reached out for help. My gratitude extends to my family, particularly my elder brother, Dr. Keivan Nalaie. His support, assistance, and     empathetic feelings towards me have been a driving force throughout my entire master's degree journey. His compassionate personality and    willingness to help me whenever I was in need have made a significant influence on my academic pursuits and the life journey.
 
  And finally, I am deeply thankful to those loved ones who played a role in my academic and personal journey. Undoubtedly, your support,     encouragement, and understanding have been influential to what I have achieved so far, and I am truly grateful for your presence in my      life.
preface: |
  This thesis includes four chapters that presents the research that I have conducted over my   master’s degree. The main goal of this thesis is to discuss commuting stress and identifying the coping strategies for motorized and active users. The case study for the middle chapters would be Santiago, Chile. This study contains some  overlaps in terms of introduction, case study and some parts of data description as the focus of those chapters are active and motorized commuters in Santiago, Chile. The first chapter of the thesis could be considered as an introduction to give a broader viewpoint of research and its objectives for each of the two subsequent chapters. The last or forth chapter serves as a through conclusion of the research, how the study contributes to other various literature and policy implications as the summary of research findings. 
  
  As a notice to the reader, my supervisor, Dr. Antonio Páez who provided me with his continuous contribution on research ideas, critical evaluations of manuscripts and editorial reviews. Dr. Beatriz Mella-Lira conducted the survey, contributed to editorial review and let me use the data as a base for my research.
  
  As main author of the whole research, I performed all of the fundamental research activities including the literature review, data preparation and cleaning, statistical analysis, model interpretation and writing of the all chapters.
bibliography: bib/thesis.bib
# Download your specific csl file and refer to it in the line below.
csl: csl/apa.csl
lot: true
lof: true
---

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of 
metadata used to produce the document.  Be careful with spacing in this header!

If you'd prefer to not include a Dedication, for example, simply delete the section entirely, or silence them (add # before each line). 

If you have other LaTeX packages you would like to include, delete the # before header-includes and list the packages after hyphens on new lines.

If you'd like to include a comment that won't be produced in your resulting file enclose it in a block like this.

If you receive a duplicate label error after knitting, make sure to delete the index.Rmd file and then knit again.
-->

```{r include_packages, include = FALSE}
# This chunk ensures that the macdown package is
# installed and loaded. This macdown package includes
# the template files for the thesis.
if(!require(remotes))
  install.packages("remotes", repos = "http://cran.rstudio.com")
if(!require(macdown))
  remotes::install_github("paezha/macdown")
library(macdown)
```

<!--
The acknowledgements, preface, dedication, and abstract are added into the PDF
version automatically by inputting them in the YAML at the top of this file.
-->

<!-- The {.unnumbered} option here means that the introduction will be 
"Chapter 0." You can also use {-} for no numbers on chapters.
-->




<!--

BEGINNING HERE ADD THE DOCUMENTS THAT CONFORM THE MAIN BODY OF THE THESIS

-->

```{r eval=!knitr::is_latex_output(), child=here::here("01-introduction.Rmd")}

```

```{r eval=!knitr::is_latex_output(), child=here::here("02-data-package.Rmd")}

```

```{r eval=!knitr::is_latex_output(), child=here::here("03-modelling.Rmd")}

```

```{r eval=!knitr::is_latex_output(), child=here::here("04-conclusion.Rmd")}

```

```{r eval=!knitr::is_latex_output(), child=here::here("99-references.Rmd")}

```
